name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  file-change:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Run Labeler Action
      uses: actions/labeler@v6

  sync:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Sync labels with closing issues
      uses: williambdean/closing-labels@v0.0.6
      with:
        exclude: "question,request discussion,help wanted,research_needed,research-done,plan_needed,plan-done,implement,implementation-done,iterate,iteration-done"
        respect_unlabeled: true
      env:
        GH_TOKEN: ${{ github.token }}
